import React from "react";
import ActivePlugin from "@/plugins/active";
import { ShieldCheck } from "lucide-react";

function CalculatorPage() {
  return (
    <div className="container mx-auto px-6 max-w-6xl py-12 space-y-6">
      <h1 className="text-2xl md:text-3xl font-bold">Surplus Calculator</h1>
      <ActivePlugin />

      {/* Disclaimer - official looking footnote */}
      <div className="mt-12">
        <div className="relative bg-muted/30 rounded-xl border border-border/50 p-6 md:p-8">
          {/* Header */}
          <div className="flex items-center gap-3 mb-4">
            <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
              <ShieldCheck className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-sm font-semibold text-foreground uppercase tracking-wide">Important Disclaimer</h2>
          </div>

          {/* Content */}
          <div className="text-xs text-muted-foreground space-y-2 leading-relaxed">
            <p>
              The Essential and Surplus Capital calculator is for illustrative purposes only.
              Like all financial planning tools, it should be understood that there are certain limitations with our calculator.
            </p>
            <p>
              Any results or contents herein can be used as an aid to an existing retirement plan, but they are rough estimates based on the information that you provided.
              Any results generated by the calculator should not be considered a replacement for a comprehensive retirement plan, investment, or financial advice.
            </p>
            <p>
              Any results can be used as an estimate for your financial future, but due to the economic unpredictability of the future, the results should not be interpreted as a guarantee for future results or a prediction of any kind.
              You should talk to a professional before making any decisions based on the results generated by this calculator.
            </p>
            <p className="pt-2 text-xs font-medium text-foreground/80 border-t border-border/50 mt-3">
              Use It Wisely accepts no liability whatsoever for any loss or costs incurred from the use of this calculator.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CalculatorPage;


