import React from "react";
import ActivePlugin from "@/plugins/active";

function CalculatorPage() {
  return (
    <div className="container mx-auto px-6 max-w-6xl py-12 space-y-6">
      <h1 className="text-2xl md:text-3xl font-bold">Surplus Calculator</h1>
      <ActivePlugin />

      {/* Disclaimer Section */}
      <div className="mt-12 border-t border-border/40 pt-8">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-lg font-semibold text-foreground mb-4">Disclaimer</h2>
          <div className="text-sm text-muted-foreground space-y-3 leading-relaxed">
            <p>
              The Essential and Surplus Capital calculator is for illustrative purposes only.
            </p>
            <p>
              Like all financial planning tools, it should be understood that there are certain limitations with our calculator.
            </p>
            <p>
              Any results or contents herein can be used as an aid to an existing retirement plan, but they are rough estimates based on the information that you provided.
            </p>
            <p>
              Any results generated by the calculator should not be considered a replacement for a comprehensive retirement plan, investment, or financial advice.
            </p>
            <p>
              Any results can be used as an estimate for your financial future, but due to the economic unpredictability of the future, the results should not be interpreted as a guarantee for future results or a prediction of any kind.
            </p>
            <p>
              You should talk to a professional before making any decisions based on the results generated by this calculator.
            </p>
            <p className="font-medium text-foreground">
              Use It Wisely accepts no liability whatsoever for any loss or costs incurred from the use of this calculator.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CalculatorPage;


